# See /assets materials.usda for default material mapping
# [surfaceTagID, surfaceTagName, defaultMaterialTagID]
default_material_map = [
    [0, 'GenericCityObject', 0],
    [1, 'Building', 0],
    [2, 'Room', 2],
    [3, 'BuildingInstallation', 3],
    [4, 'BuildingFurniture', 3],
    [5, 'Door', 3],
    [6, 'Window', 4],
    [7, 'CityFurniture', 0],
    [8, 'Track', 0],
    [9, 'Road', 0],
    [10, 'Railway', 0],
    [11, 'Square', 0],
    [12, 'PlantCover', 0],
    [13, 'SolitaryVegetationObject', 0],
    [14, 'WaterBody', 0],
    [15, 'ReliefFeature', 0],
    [16, 'ReliefComponent', 0],
    [17, 'TINRelief', 0],
    [18, 'MassPointRelief', 0],
    [19, 'BreaklineRelief', 0],
    [20, 'RasterRelief', 0],
    [21, 'LandUse', 0],
    [22, 'Tunnel', 0],
    [23, 'Bridge', 0],
    [24, 'BridgeConstructionElement', 0],
    [25, 'BridgeInstallation', 0],
    [26, 'BridgePart', 0],
    [27, 'BuildingPart', 0],
    [28, 'WallSurface', 2],
    [29, 'RoofSurface', 0],
    [30, 'GroundSurface', 12],
    [31, 'ClosureSurface', 0],
    [32, 'FloorSurface', 9],
    [33, 'InteriorWallSurface', 2],
    [34, 'CeilingSurface', 5],
    [35, 'CityObjectGroup', 0],
    [36, 'OuterCeilingSurface', 5],
    [37, 'OuterFloorSurface', 9],
    ]


